routes/web.php
<?php

use Illuminate\Routing\Route as RoutingRoute;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//...... Auth route
Auth::routes();


// Home
Route::get('/', 'GuestHomeController@index');

//routing untuk visi dan misi
Route::get('/visi-misi', function () {
    return view('guests.menus.visi-misi');
})->name('visi-misi');

//routing untuk tujuan dan fungsi
Route::get('/tujuan', function () {
    return view('guests.menus.tujuan');
})->name('tujuan');

//routing untuk struktur dan fungsi
Route::get('/struktur-organisasi', function () {
    return view('guests.menus.struktur-organisasi');
})->name('struktur-organisasi');

//routing untuk berita
Route::get('/berita', function () {
    return view('guests.menus.berita');
});

//routing untuk detail berita
// nama_berita ini diambil berdasarkan link nama berita. bisa juga jadi id nya
Route::get('/berita/nama_berita', function () {
    return view('guests/detail_berita');
});


// routing untuk halaman user

Route::get('/lapor_bencana', function () {
    return view('guests/formlapor');
});
Route::get('/home', 'HomeController@index')->name('home');
//Route::resource('/reports', 'ReportController'); 

/**
 * E-Lapor
 */
Route::get('/elapor-bencana/create', 'ReportController@createReportByGuest')->name('reports.guest.create');
Route::post('/elapor-bencana', 'ReportController@store')->name('reports.store');
Route::get('/elapor-bencana/{report}', 'ReportController@showReport')->name('reports.guest.show');

/**
 * Route Berita
 */
Route::get('/berita', 'AnnouncementsController@getNews')->name('guests.news');

Route::get('/berita/{announcement}', 'AnnouncementsController@showNews')->name('guest_news.show');

Route::get('/kegiatan', 'AnnouncementsController@getActivities')->name('guests.activities');

Route::get('/kegiatan/{announcement}', 'AnnouncementsController@showActivity')->name('guest_activity.show');

Route::get('/findVillages', 'VillageController@findVillagesById')->name('getVillages');

Route::middleware(['auth', 'admin'])->group(function () {
    /**
     * Admin pages' route
     */
    Route::get('/admin', 'HomeController@admin')->name('admin');

    /**
     * Announcement's categories routes
     */
    Route::resource('/categories', 'CategoriesController');

    /**
     * News or Activity route 
     */

    Route::resource('/announcements', 'AnnouncementsController');
    /**
     * Logistik
     */
    Route::resource('/logistics', 'LogisticsController');

    // Cari Logistiks
    Route::get('/search', 'LogisticsController@search')->name('logistics.search');

    /**
     * Jenis Barang logisti
     */
    Route::resource('/logistics-categories', 'LogisticsCategoryController');


    /**
     * Disaster Report route
     */

    Route::get('/laporbencana', 'ReportController@index')->name('reports.index');
    Route::get('/laporbencana/create', 'ReportController@create')->name('reports.create');
    Route::get('/laporbencana/{report}/edit', 'ReportController@edit')->name('reports.edit');
    Route::patch('/laporbencana/{report}', 'ReportController@update')->name('reports.update');
    Route::get('/lapor-bencana/{report}', 'ReportController@show')->name('reports.show');
    Route::delete('/laporbencana/{report}/delete', 'ReportController@destroy')->name('reports.destroy');

    Route::get('/laporbencana/{report}', 'ReportController@validateReport')->name('reports.validate');


    /**
     * Disaster's Route 
     */
    //  Route::resource('/disasters', 'DisasterController');
    Route::get('/jenisbencana', 'DisasterController@index')->name('disasters.index');
    Route::get('/jenisbencana/create', 'DisasterController@create')->name('disasters.create');
    Route::post('/jenisbencana', 'DisasterController@store')->name('disasters.store');
    Route::get('/jenisbencana/{disaster}/edit', 'DisasterController@edit')->name('disasters.edit');
    Route::patch('/jenisbencana/{disaster}', 'DisasterController@update')->name('disasters.update');
    Route::delete('/jenisbencana/{disaster}/delete', 'DisasterController@destroy')->name('disasters.destroy');

    /** Subdistrict's(Kecamatan) route  */
    Route::get('/kecamatan', 'SubdistrictController@index')->name('subdistricts.index');
    Route::get('/kecamatan/create', 'SubdistrictController@create')->name('subdistricts.create');
    Route::post('/kecamatan', 'SubdistrictController@store')->name('subdistricts.store');
    Route::get('/kecamatan/{subdistrict}/edit', 'SubdistrictController@edit')->name('subdistricts.edit');
    Route::patch('/kecamatan/{subdistrict}', 'SubdistrictController@update')->name('subdistricts.update');
    Route::delete('kecamatan/{subdistrict}/delete', 'SubdistrictController@destroy')->name('subdistricts.destroy');

    /** Village's(Desa/Kelurahan) route */
    Route::get('/kecamatan/{subdistrict}/desa', 'VillageController@index')->name('villages.index');
    Route::get('/kecamatan/{subdistrict}/desa/create', 'VillageController@create')->name('villages.create');
    Route::post('/kecamatan/{subdistrict}/desa', 'VillageController@store')->name('villages.store');
    Route::get('/kecamatan/{subdistrict}/desa/{village}/edit', 'VillageController@edit')->name('villages.edit');
    Route::patch('/kecamatan/{subdistrict}/desa/{village}', 'VillageController@update')->name('villages.update');
    Route::delete('/kecamatan/{subdistrict}/desa/{village}/delete', 'VillageController@destroy')->name('villages.destroy');
});

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Admin BPBD</title>

    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('dist/css/adminlte.min.css')}}">

    @include('layouts.css')

    @yield('css')

</head>

<body class="hold-transition sidebar-mini layout-fixed" style="background: #f4f6f9">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="{{asset('img/logo.png')}}" alt="logo BPBD" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Admin BPBD</span>
            </a>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                    <li class="nav-item has-treeview menu-open">
                        <a href="#" class="nav-link active">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>
                                Dashboard
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                    </li>
                    <!--Berita-->
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-table"></i>
                            <p>
                                Berita
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{route('announcements.index')}}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Berita</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('categories.index')}}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Kategory Berita</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <!-- ./ Berita-->
                    <!--E-Lapor-->
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-edit"></i>
                            <p>
                                E-Lapor
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{route('reports.index')}}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Laporan</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('disasters.index')}}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Daftar Bencana</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('subdistricts.index')}}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Kecamatan</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <!-- ./ E-Lapor-->

                    <!--Logistik-->
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-chart-pie"></i>
                            <p>
                                Logistik
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{route('logistics.index')}}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Data Logistik</p>
                                </a>
                            </li>

                        </ul>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{route('logistics-categories.index')}}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Jenis Barang Logistik</p>
                                </a>
                            </li>

                        </ul>
                    </li>
                    <!-- ./ Logistik-->
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
    </aside>

    <!-- Content-->
    <div class="content-wrapper">
        <section class="content m-4">
            @if(session()->has('success'))
            @include('partials.successflash')
            @endif

            @if(session()->has('error'))
            @include('partials.errorflash')
            @endif

            @yield('content')
        </section>
    </div>
    <!-- /.Content-->

    <footer class="main-footer">
        <strong>Copyright &copy;2020 <a href="#">Admin BPBD</a>.</strong>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    @yield('scripts')
    <!-- jQuery -->
    <script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('dist/js/adminlte.js')}}"></script>
    <script src="../js/bootstrap-tooltip.js"></script>

    <script src="{{asset('plugins/bootstrap/js/bootstrap.min.js')}}"></script>
    <script src="../js/bootstrap-alert.js"></script>
</body>

</html>

resources/views/admin/index.blade.php
@extends('admin.app')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper" style="margin: auto">
    <!-- Content Header (Page header) -->

    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Dashboard</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard v1</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->

    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{$reportsCount}}</h3>

                            <p>Jumlah Laporan</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-bag"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>{{$newsCount}}</h3>

                            <p>Berita</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>Kecamatan</h3>

                            <p>{{$subdistrictCount}}</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@endsection