routes/web.php
<?php

use Illuminate\Routing\Route as RoutingRoute;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//...... Auth route
Auth::routes();


// Home
Route::get('/', 'GuestHomeController@index');

//routing untuk visi dan misi
Route::get('/visi-misi', function () {
    return view('guests.menus.visi-misi');
})->name('visi-misi');

//routing untuk tujuan dan fungsi
Route::get('/tujuan', function () {
    return view('guests.menus.tujuan');
})->name('tujuan');

//routing untuk struktur dan fungsi
Route::get('/struktur-organisasi', function () {
    return view('guests.menus.struktur-organisasi');
})->name('struktur-organisasi');

//routing untuk berita
Route::get('/berita', function () {
    return view('guests.menus.berita');
});

//routing untuk detail berita
// nama_berita ini diambil berdasarkan link nama berita. bisa juga jadi id nya
Route::get('/berita/nama_berita', function () {
    return view('guests/detail_berita');
});


// routing untuk halaman user

Route::get('/lapor_bencana', function () {
    return view('guests/formlapor');
});
Route::get('/home', 'HomeController@index')->name('home');
//Route::resource('/reports', 'ReportController'); 

/**
 * E-Lapor
 */
Route::get('/elapor-bencana/create', 'ReportController@createReportByGuest')->name('reports.guest.create');
Route::post('/elapor-bencana', 'ReportController@store')->name('reports.store');
Route::get('/elapor-bencana/{report}', 'ReportController@showReport')->name('reports.guest.show');

/**
 * Route Berita
 */
Route::get('/berita', 'AnnouncementsController@getNews')->name('guests.news');

Route::get('/berita/{announcement}', 'AnnouncementsController@showNews')->name('guest_news.show');

Route::get('/kegiatan', 'AnnouncementsController@getActivities')->name('guests.activities');

Route::get('/kegiatan/{announcement}', 'AnnouncementsController@showActivity')->name('guest_activity.show');

Route::get('/findVillages', 'VillageController@findVillagesById')->name('getVillages');

Route::middleware(['auth', 'admin'])->group(function () {
    /**
     * Admin pages' route
     */
    Route::get('/admin', 'HomeController@admin')->name('admin');

    /**
     * Announcement's categories routes
     */
    Route::resource('/categories', 'CategoriesController');

    /**
     * News or Activity route 
     */

    Route::resource('/announcements', 'AnnouncementsController');
    /**
     * Logistik
     */
    Route::resource('/logistics', 'LogisticsController');

    // Cari Logistiks
    Route::get('/search', 'LogisticsController@search')->name('logistics.search');

    /**
     * Jenis Barang logisti
     */
    Route::resource('/logistics-categories', 'LogisticsCategoryController');


    /**
     * Disaster Report route
     */

    Route::get('/laporbencana', 'ReportController@index')->name('reports.index');
    Route::get('/laporbencana/create', 'ReportController@create')->name('reports.create');
    Route::get('/laporbencana/{report}/edit', 'ReportController@edit')->name('reports.edit');
    Route::patch('/laporbencana/{report}', 'ReportController@update')->name('reports.update');
    Route::get('/lapor-bencana/{report}', 'ReportController@show')->name('reports.show');
    Route::delete('/laporbencana/{report}/delete', 'ReportController@destroy')->name('reports.destroy');

    Route::get('/laporbencana/{report}', 'ReportController@validateReport')->name('reports.validate');


    /**
     * Disaster's Route 
     */
    //  Route::resource('/disasters', 'DisasterController');
    Route::get('/jenisbencana', 'DisasterController@index')->name('disasters.index');
    Route::get('/jenisbencana/create', 'DisasterController@create')->name('disasters.create');
    Route::post('/jenisbencana', 'DisasterController@store')->name('disasters.store');
    Route::get('/jenisbencana/{disaster}/edit', 'DisasterController@edit')->name('disasters.edit');
    Route::patch('/jenisbencana/{disaster}', 'DisasterController@update')->name('disasters.update');
    Route::delete('/jenisbencana/{disaster}/delete', 'DisasterController@destroy')->name('disasters.destroy');

    /** Subdistrict's(Kecamatan) route  */
    Route::get('/kecamatan', 'SubdistrictController@index')->name('subdistricts.index');
    Route::get('/kecamatan/create', 'SubdistrictController@create')->name('subdistricts.create');
    Route::post('/kecamatan', 'SubdistrictController@store')->name('subdistricts.store');
    Route::get('/kecamatan/{subdistrict}/edit', 'SubdistrictController@edit')->name('subdistricts.edit');
    Route::patch('/kecamatan/{subdistrict}', 'SubdistrictController@update')->name('subdistricts.update');
    Route::delete('kecamatan/{subdistrict}/delete', 'SubdistrictController@destroy')->name('subdistricts.destroy');

    /** Village's(Desa/Kelurahan) route */
    Route::get('/kecamatan/{subdistrict}/desa', 'VillageController@index')->name('villages.index');
    Route::get('/kecamatan/{subdistrict}/desa/create', 'VillageController@create')->name('villages.create');
    Route::post('/kecamatan/{subdistrict}/desa', 'VillageController@store')->name('villages.store');
    Route::get('/kecamatan/{subdistrict}/desa/{village}/edit', 'VillageController@edit')->name('villages.edit');
    Route::patch('/kecamatan/{subdistrict}/desa/{village}', 'VillageController@update')->name('villages.update');
    Route::delete('/kecamatan/{subdistrict}/desa/{village}/delete', 'VillageController@destroy')->name('villages.destroy');
});

app/Announcement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;


class Announcement extends Model
{
    protected $fillable = ['title', 'body', 'image', 'category_id', 'announcement_date'];

    public function deleteImage()
    {
        Storage::delete($this->image);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/AnnouncementsController.php
<?php

namespace App\Http\Controllers;

use App\Announcement;
use App\Category;
use App\Http\Requests\announcements\CreateAnnouncementsRequest;
use App\Http\Requests\announcements\UpdateAnnouncementsRequest;

use Illuminate\Http\Request;

class AnnouncementsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $announcements = Announcement::all();
        return view('admin.announcements.index', compact('announcements'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.announcements.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateAnnouncementsRequest $request)
    {
        // dd($request);
        $image = request()->image->store('announcements');

        Announcement::create([
            'title' => $request['title'],
            'body' => $request['body'],
            'announcement_date' => $request['announcement_date'],
            'image' => $image,
            'category_id' => $request['category'],
        ]);

        session()->flash('success', 'Berhasil membuat berita baru');

        return redirect(route('announcements.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Announcement  $announcement
     * @return \Illuminate\Http\Response
     */
    public function show(Announcement $announcement)
    {
        return view('admin.announcements.show', compact('announcement'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Announcement  $announcement
     * @return \Illuminate\Http\Response
     */
    public function edit(Announcement $announcement)
    {
        $categories = Category::all();
        return view('admin.announcements.edit', compact([
            'announcement',
            'categories'
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Announcement  $announcement
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAnnouncementsRequest $request, Announcement $announcement)
    {
        $data = $request->only(['title', 'body', 'category_id']);

        if ($request->hasFile('image')) {
            $image = $request->image->store('announcements');
            $announcement->deleteImage();
            $data['image'] = $image;
        }
        $announcement->update($data);
        session()->flash('success', 'Berhasil memperbarui berita');
        return redirect(route('announcements.show', compact('announcement')));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Announcement  $announcement
     * @return \Illuminate\Http\Response
     */
    public function destroy(Announcement $announcement)
    {
        $announcement->deleteImage();
        $announcement->delete();
        return redirect(route('announcements.index'));
    }
    public function getNews()
    {
        $announcements = Announcement::where('category_id', 1)->get();
        return view('guests.announcements.index', compact('announcements'));
    }
    public function getActivities()
    {
        $announcements = Announcement::where('category_id', '<>', 1)->get();
        return view('guests.announcements.index', compact('announcements'));
    }

    public function showActivity(Announcement $announcement)
    {
        return view('guests.announcements.show', compact('announcement'));
    }
    public function showNews(Announcement $announcement)
    {
        return view('guests.announcements.show', compact('announcement'));
    }
}

resources/views/admin/announcements/create.blade.php
@extends('admin.app')
@section('content')
<div class="container">
    <div class="col-md-8">
        <div class="card card-default">
            <div class="card-header">Buat Berita</div>
            <form action="{{route('announcements.store')}}" method="POST" enctype="multipart/form-data">
                @include('admin.announcements.form',[
                'buttonText' => 'Create',
                'announcement'=>null
                ])
            </form>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
@endsection

@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.css">
@endsection

resources/views/admin/announcements/edit.blade.php
@extends('admin.app')
@section('content')
<div class="card card-default">
    <div class="card-header">Update Post</div>
    <form action="{{route('announcements.update', $announcement)}}" method="POST" enctype="multipart/form-data">
        @method('PATCH')
        @include('admin.announcements.form', [
        'buttonText' => 'Update Berita'
        ])
    </form>
</div>
@endsection

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
@endsection
@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
@endsection

resources/views/admin/announcements/form.blade.php
@csrf
<div class="card-body">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="title" name="title" id="title" class="form-control" value="{{isset($announcement) ? $announcement->title :''}}">
        @if($errors->has('title'))
        <p class="text-danger text-sm">{{$errors->first('title')}}</p>
        @endif
    </div>
    <div class="form-group">
        <label for="announcement_date">Waktu kejadian </label>
        <input type="text" name="announcement_date" id="announcement_date" class="form-control" value="{{isset($announcement)?$announcement->announcement_name:''}}">
        @if($errors->has('announcement_date'))
        <p class="text-danger text-sm">{{$errors->first('announcement_date')}}</p>
        @endif
    </div>
    <div class="form-group">
        <label for="body">Isi berita</label>
        <input id="body" type="hidden" name="body" value="{{isset($announcement)? $announcement->body:''}}">
        <trix-editor input="body"></trix-editor>
        @if($errors->has('body'))
        <p class="text-danger text-sm">{{$errors->first('body')}}</p>
        @endif
    </div>
    <div class="form-group">
        <label for="image">Image</label>
        @if(isset($announcement))
        <img class="img-fluid rounded my-4" src="/storage/{{$announcement->image}}" alt="img" style="height:300px; width:400px">
        @endif
        <input type="file" name="image" id="image" class="form-control">
        @if($errors->has('image'))
        <p class="text-danger text-sm">{{$errors->first('image')}}</p>
        @endif
    </div>
    <div class="form-group">
        <label for="category">Category</label>
        <select name="category" id="category" class="form-control">
            @foreach($categories as $category)
            <option value="{{$category->id}}">{{$category->name}}</option>
            @endforeach
        </select>
        @if($errors->has('category'))
        <p class="text-danger text-sm">{{$errors->first('category')}}</p>
        @endif
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-success btn-sm">{{$buttonText}}</button>
    </div>
</div>

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
    flatpickr('#announcement_date', {
        enableTime: true,
        enableSeconds: true
    })
</script>
@endsection

@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endsection

resources/views/admin/announcements/index.blade.php
@extends('admin.app')
@section('content')
<?php $ctr = 0; ?>
<!-- Content Wrapper. Contains page content -->
<div class="row">
    <a href="{{route('announcements.create')}}" class="btn btn-success btn-sm m-4">Create Berita</a>
</div>


<div class="container">
    <table class="table table-hover">
        @if($announcements->count())
        <thead class="bg-orange text-white">
            <th>No</th>
            <th>Title</th>
            <th>Tanggal</th>
            <th>Kategory</th>
            <th>Aksi</th>
        </thead>
        <tbody>
            @foreach($announcements as $announcement)
            <?php $ctr++ ?>
            <tr>
                <td>{{$ctr}}</td>
                <td>{{$announcement->title}}</td>
                <td>{{$announcement->announcement_date}}</td>
                <td>{{$announcement->category->name}}</td>
                <td>
                    <div class="row mx-auto">
                        <span>
                            <a href="{{route('announcements.show', $announcement)}}">
                                <i class="nav-icon fas fa-eye "></i>
                            </a>
                        </span>
                        <span class="mx-2">
                            <a href="{{route('announcements.edit', $announcement)}}">
                                <i class="nav-icon fas fa-edit"></i>
                            </a>
                        </span>
                        <form action="{{route('announcements.destroy', $announcement)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <span>
                                <button class="border-0 bg-light" type="submit">
                                    <i class="nav-icon fas fa-trash text-danger"></i>
                                </button>
                        </form>

                    </div>
                </td>
            </tr>
            @endforeach
        </tbody>
        @else
        <h4>
            <center>Belum ada Berita/Kegiatan</center>
        </h4>
        @endif
    </table>
</div>
@endsection

resources/views/admin/announcements/show.blade.php
@extends('admin.app')
@section('content')

<div class="row">

    <!-- Post Content Column -->
    <div class="container">
        <h1 class="mt-4 mb-3"> {{$announcement->title}} </h1>
        <!-- Preview Image -->
        <img class="img-fluid rounded" src="/storage/{{$announcement->image}}" alt="">
        <hr>

        <!-- Date/Time -->
        <p class="my-2">{{formatDate($announcement->announcement_date)}}</p>
        <hr>
        <div>{!! $announcement->body !!}</div>
    </div>
</div>
@endsection