routes/web.php
<?php

use Illuminate\Routing\Route as RoutingRoute;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//...... Auth route
Auth::routes();


// Home
Route::get('/', 'GuestHomeController@index');

//routing untuk visi dan misi
Route::get('/visi-misi', function () {
    return view('guests.menus.visi-misi');
})->name('visi-misi');

//routing untuk tujuan dan fungsi
Route::get('/tujuan', function () {
    return view('guests.menus.tujuan');
})->name('tujuan');

//routing untuk struktur dan fungsi
Route::get('/struktur-organisasi', function () {
    return view('guests.menus.struktur-organisasi');
})->name('struktur-organisasi');

//routing untuk berita
Route::get('/berita', function () {
    return view('guests.menus.berita');
});

//routing untuk detail berita
// nama_berita ini diambil berdasarkan link nama berita. bisa juga jadi id nya
Route::get('/berita/nama_berita', function () {
    return view('guests/detail_berita');
});


// routing untuk halaman user

Route::get('/lapor_bencana', function () {
    return view('guests/formlapor');
});
Route::get('/home', 'HomeController@index')->name('home');
//Route::resource('/reports', 'ReportController'); 

/**
 * E-Lapor
 */
Route::get('/elapor-bencana/create', 'ReportController@createReportByGuest')->name('reports.guest.create');
Route::post('/elapor-bencana', 'ReportController@store')->name('reports.store');
Route::get('/elapor-bencana/{report}', 'ReportController@showReport')->name('reports.guest.show');

/**
 * Route Berita
 */
Route::get('/berita', 'AnnouncementsController@getNews')->name('guests.news');

Route::get('/berita/{announcement}', 'AnnouncementsController@showNews')->name('guest_news.show');

Route::get('/kegiatan', 'AnnouncementsController@getActivities')->name('guests.activities');

Route::get('/kegiatan/{announcement}', 'AnnouncementsController@showActivity')->name('guest_activity.show');

Route::get('/findVillages', 'VillageController@findVillagesById')->name('getVillages');

Route::middleware(['auth', 'admin'])->group(function () {
    /**
     * Admin pages' route
     */
    Route::get('/admin', 'HomeController@admin')->name('admin');

    /**
     * Announcement's categories routes
     */
    Route::resource('/categories', 'CategoriesController');

    /**
     * News or Activity route 
     */

    Route::resource('/announcements', 'AnnouncementsController');
    /**
     * Logistik
     */
    Route::resource('/logistics', 'LogisticsController');

    // Cari Logistiks
    Route::get('/search', 'LogisticsController@search')->name('logistics.search');

    /**
     * Jenis Barang logisti
     */
    Route::resource('/logistics-categories', 'LogisticsCategoryController');


    /**
     * Disaster Report route
     */

    Route::get('/laporbencana', 'ReportController@index')->name('reports.index');
    Route::get('/laporbencana/create', 'ReportController@create')->name('reports.create');
    Route::get('/laporbencana/{report}/edit', 'ReportController@edit')->name('reports.edit');
    Route::patch('/laporbencana/{report}', 'ReportController@update')->name('reports.update');
    Route::get('/lapor-bencana/{report}', 'ReportController@show')->name('reports.show');
    Route::delete('/laporbencana/{report}/delete', 'ReportController@destroy')->name('reports.destroy');

    Route::get('/laporbencana/{report}', 'ReportController@validateReport')->name('reports.validate');


    /**
     * Disaster's Route 
     */
    //  Route::resource('/disasters', 'DisasterController');
    Route::get('/jenisbencana', 'DisasterController@index')->name('disasters.index');
    Route::get('/jenisbencana/create', 'DisasterController@create')->name('disasters.create');
    Route::post('/jenisbencana', 'DisasterController@store')->name('disasters.store');
    Route::get('/jenisbencana/{disaster}/edit', 'DisasterController@edit')->name('disasters.edit');
    Route::patch('/jenisbencana/{disaster}', 'DisasterController@update')->name('disasters.update');
    Route::delete('/jenisbencana/{disaster}/delete', 'DisasterController@destroy')->name('disasters.destroy');

    /** Subdistrict's(Kecamatan) route  */
    Route::get('/kecamatan', 'SubdistrictController@index')->name('subdistricts.index');
    Route::get('/kecamatan/create', 'SubdistrictController@create')->name('subdistricts.create');
    Route::post('/kecamatan', 'SubdistrictController@store')->name('subdistricts.store');
    Route::get('/kecamatan/{subdistrict}/edit', 'SubdistrictController@edit')->name('subdistricts.edit');
    Route::patch('/kecamatan/{subdistrict}', 'SubdistrictController@update')->name('subdistricts.update');
    Route::delete('kecamatan/{subdistrict}/delete', 'SubdistrictController@destroy')->name('subdistricts.destroy');

    /** Village's(Desa/Kelurahan) route */
    Route::get('/kecamatan/{subdistrict}/desa', 'VillageController@index')->name('villages.index');
    Route::get('/kecamatan/{subdistrict}/desa/create', 'VillageController@create')->name('villages.create');
    Route::post('/kecamatan/{subdistrict}/desa', 'VillageController@store')->name('villages.store');
    Route::get('/kecamatan/{subdistrict}/desa/{village}/edit', 'VillageController@edit')->name('villages.edit');
    Route::patch('/kecamatan/{subdistrict}/desa/{village}', 'VillageController@update')->name('villages.update');
    Route::delete('/kecamatan/{subdistrict}/desa/{village}/delete', 'VillageController@destroy')->name('villages.destroy');
});

app/LogisticsCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LogisticsCategory extends Model
{
    protected $fillable = ['name'];

    public function logistics()
    {
        return $this->hasMany(Logistics::class);
    }
}

app/Http/Controllers/LogisticsCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\logistics_categories\CreateLogisticsCategoryRequest;
use App\Http\Requests\logistics_categories\UpdateLogisticsCategoryRequest;
use App\LogisticsCategory;
use Illuminate\Http\Request;

class LogisticsCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $logisticsCategories = LogisticsCategory::all();
        return view('admin.logistics_categories.index', compact('logisticsCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.logistics_categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateLogisticsCategoryRequest $request)
    {
        LogisticsCategory::create([
            'name' => $request['name'],
        ]);
        session()->flash('success', 'Berhasil membuat kategory barang logistik');

        return redirect(route('logistics-categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\LogisticsCategory  $logisticsCategory
     * @return \Illuminate\Http\Response
     */
    public function show(LogisticsCategory $logisticsCategory)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\LogisticsCategory  $logisticsCategory
     * @return \Illuminate\Http\Response
     */
    public function edit(LogisticsCategory $logisticsCategory)
    {
        return view('admin.logistics_categories.edit', compact('logisticsCategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\LogisticsCategory  $logisticsCategory
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateLogisticsCategoryRequest $request, LogisticsCategory $logisticsCategory)
    {
        $logisticsCategory->update([
            'name' => $request['name'],
        ]);

        session()->flash('success', 'Berhasil mengedit kategory barang logistik');

        return redirect(route('logistics-categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\LogisticsCategory  $logisticsCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy(LogisticsCategory $logisticsCategory)
    {
        if ($logisticsCategory->logistics->count()) {
            session()->flash('error', 'Tidak dapat menghapus kategori logistik karena sudah digunakan dalam data logistik');
            return redirect(route('logistics-categories.index'));
        }
        $logisticsCategory->delete();
        session()->flash('success', 'Berhasil menghapus kategory');
        return redirect(route('logistics-categories.index'));
    }
}

resources/views/admin/logistics_categories/create.blade.php
@extends('admin.app')
@section('content')
<div class="container">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Membuat Jenis Barang Logistik Baru</div>
            <div class="card-body">
                <form action="{{route('logistics-categories.store')}}" method="POST">
                    @include('admin.logistics_categories.form',[
                    'buttonText' => 'Create',
                    'logisticsCategory' => new App\LogisticsCategory
                    ])
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/logistics_categories/edit.blade.php
@extends('admin.app')
@section('content')
<div class="container">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Membuat Kecamatan Baru</div>
            <div class="card-body">
                <form action="{{route('logistics-categories.update', $logisticsCategory)}}" method="POST">
                    @method('PATCH')
                    @include('admin.logistics_categories.form',[
                    'buttonText' => 'Edit'
                    ])
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/logistics_categories/form.blade.php
  @csrf
  <div class="form-group">
      <label for="name">Nama Kategory</label>
      <input type="text" name="name" id="name" class="form-control" value="{{$logisticsCategory->name}}">
      @if($errors->has('name'))
      <div class="text-danger text-sm">{{ $errors->first('name') }}</div>
      @endif
  </div>
  <div class="form-group">
      <button class="btn btn-success" type="submit">{{$buttonText}}</button>
  </div>

resources/views/admin/logistics_categories/index.blade.php
@extends('admin.app')
@section('content')
<?php $no = 0; ?>
<div class="container">
    <div class="row">
        <a href="{{route('logistics-categories.create')}}" class="btn btn-success my-4 ml-3">Tambah Jenis Barang Logistik</a>
    </div>
    <div class="row">
        <div class="col-md-10 mx-auto">

            @if($logisticsCategories->count())
            <table class="table bg-light">
                <thead class="table-primary">
                    <tr>
                        <th scope="col-sm-1">#</th>
                        <th scope="col-sm-5">Name</th>
                        <th scope="col-sm-5">
                            <center>Action</center>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($logisticsCategories as $logisticsCategory)

                    <tr>
                        <?php $no++ ?>
                        <td scope="row border-0">{{$no}}</td>
                        <td><a href="{{route('villages.index', $logisticsCategory)}}">{{$logisticsCategory->name}}</a></td>
                        <td class="d-flex justify-content-center ">
                            <div class="row">
                                <span>
                                    <a href="{{route('logistics-categories.edit', $logisticsCategory)}}">
                                        <i class="nav-icon fas fa-eye text-info"></i>
                                    </a>
                                </span>
                                <form action="{{route('logistics-categories.destroy', $logisticsCategory)}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <span class="">
                                        <button class="border-0 bg-light" type="submit">
                                            <i class="nav-icon fas fa-trash text-danger"></i>
                                        </button>
                                </form>

                            </div>

                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            @else
            <h3>
                <center>Belum ada Jenis Barang</center>
            </h3>
            @endif
        </div>
    </div>
</div>
@endsection