routes/web.php
<?php

use Illuminate\Routing\Route as RoutingRoute;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//...... Auth route
Auth::routes();


// Home
Route::get('/', 'GuestHomeController@index');

//routing untuk visi dan misi
Route::get('/visi-misi', function () {
    return view('guests.menus.visi-misi');
})->name('visi-misi');

//routing untuk tujuan dan fungsi
Route::get('/tujuan', function () {
    return view('guests.menus.tujuan');
})->name('tujuan');

//routing untuk struktur dan fungsi
Route::get('/struktur-organisasi', function () {
    return view('guests.menus.struktur-organisasi');
})->name('struktur-organisasi');

//routing untuk berita
Route::get('/berita', function () {
    return view('guests.menus.berita');
});

//routing untuk detail berita
// nama_berita ini diambil berdasarkan link nama berita. bisa juga jadi id nya
Route::get('/berita/nama_berita', function () {
    return view('guests/detail_berita');
});


// routing untuk halaman user

Route::get('/lapor_bencana', function () {
    return view('guests/formlapor');
});
Route::get('/home', 'HomeController@index')->name('home');
//Route::resource('/reports', 'ReportController'); 

/**
 * E-Lapor
 */
Route::get('/elapor-bencana/create', 'ReportController@createReportByGuest')->name('reports.guest.create');
Route::post('/elapor-bencana', 'ReportController@store')->name('reports.store');
Route::get('/elapor-bencana/{report}', 'ReportController@showReport')->name('reports.guest.show');

/**
 * Route Berita
 */
Route::get('/berita', 'AnnouncementsController@getNews')->name('guests.news');

Route::get('/berita/{announcement}', 'AnnouncementsController@showNews')->name('guest_news.show');

Route::get('/kegiatan', 'AnnouncementsController@getActivities')->name('guests.activities');

Route::get('/kegiatan/{announcement}', 'AnnouncementsController@showActivity')->name('guest_activity.show');

Route::get('/findVillages', 'VillageController@findVillagesById')->name('getVillages');

Route::middleware(['auth', 'admin'])->group(function () {
    /**
     * Admin pages' route
     */
    Route::get('/admin', 'HomeController@admin')->name('admin');

    /**
     * Announcement's categories routes
     */
    Route::resource('/categories', 'CategoriesController');

    /**
     * News or Activity route 
     */

    Route::resource('/announcements', 'AnnouncementsController');
    /**
     * Logistik
     */
    Route::resource('/logistics', 'LogisticsController');

    // Cari Logistiks
    Route::get('/search', 'LogisticsController@search')->name('logistics.search');

    /**
     * Jenis Barang logisti
     */
    Route::resource('/logistics-categories', 'LogisticsCategoryController');


    /**
     * Disaster Report route
     */

    Route::get('/laporbencana', 'ReportController@index')->name('reports.index');
    Route::get('/laporbencana/create', 'ReportController@create')->name('reports.create');
    Route::get('/laporbencana/{report}/edit', 'ReportController@edit')->name('reports.edit');
    Route::patch('/laporbencana/{report}', 'ReportController@update')->name('reports.update');
    Route::get('/lapor-bencana/{report}', 'ReportController@show')->name('reports.show');
    Route::delete('/laporbencana/{report}/delete', 'ReportController@destroy')->name('reports.destroy');

    Route::get('/laporbencana/{report}', 'ReportController@validateReport')->name('reports.validate');


    /**
     * Disaster's Route 
     */
    //  Route::resource('/disasters', 'DisasterController');
    Route::get('/jenisbencana', 'DisasterController@index')->name('disasters.index');
    Route::get('/jenisbencana/create', 'DisasterController@create')->name('disasters.create');
    Route::post('/jenisbencana', 'DisasterController@store')->name('disasters.store');
    Route::get('/jenisbencana/{disaster}/edit', 'DisasterController@edit')->name('disasters.edit');
    Route::patch('/jenisbencana/{disaster}', 'DisasterController@update')->name('disasters.update');
    Route::delete('/jenisbencana/{disaster}/delete', 'DisasterController@destroy')->name('disasters.destroy');

    /** Subdistrict's(Kecamatan) route  */
    Route::get('/kecamatan', 'SubdistrictController@index')->name('subdistricts.index');
    Route::get('/kecamatan/create', 'SubdistrictController@create')->name('subdistricts.create');
    Route::post('/kecamatan', 'SubdistrictController@store')->name('subdistricts.store');
    Route::get('/kecamatan/{subdistrict}/edit', 'SubdistrictController@edit')->name('subdistricts.edit');
    Route::patch('/kecamatan/{subdistrict}', 'SubdistrictController@update')->name('subdistricts.update');
    Route::delete('kecamatan/{subdistrict}/delete', 'SubdistrictController@destroy')->name('subdistricts.destroy');

    /** Village's(Desa/Kelurahan) route */
    Route::get('/kecamatan/{subdistrict}/desa', 'VillageController@index')->name('villages.index');
    Route::get('/kecamatan/{subdistrict}/desa/create', 'VillageController@create')->name('villages.create');
    Route::post('/kecamatan/{subdistrict}/desa', 'VillageController@store')->name('villages.store');
    Route::get('/kecamatan/{subdistrict}/desa/{village}/edit', 'VillageController@edit')->name('villages.edit');
    Route::patch('/kecamatan/{subdistrict}/desa/{village}', 'VillageController@update')->name('villages.update');
    Route::delete('/kecamatan/{subdistrict}/desa/{village}/delete', 'VillageController@destroy')->name('villages.destroy');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];

    public function announcements()
    {
        return $this->hasMany(Announcement::class);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    protected $fillable = ['name'];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        Category::create($this->validateRequest());
        return redirect('/admin');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Category $category)
    {
        $category->update($this->validateRequest());
        return redirect('/admin');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect('/admin');
    }
    private function validateRequest()
    {
        return request()->validate(['name' => 'required|unique:categories']);
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.app')
@section('content')
<div class="col-md-4"></div>
<div class="col-md-8 items-center">
    <div class="card card-default">
        <div class="card-header">Create Category</div>
        <form action="{{route('categories.store')}}" method="POST">
            @include('admin.categories.form',[
            'buttonText' => 'Create Category',
            'category' => new App\Category
            ]);
        </form>
        @include('partials.errors')
    </div>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.app')
@section('content')
<div class="col-md-8">
    <div class="card card-default">
        <div class="card-header">Update Category</div>
        <form action="{{route('categories.update', $category)}}" method="POST">
            @method('PATCH')
            @include('admin.categories.form',[
            'buttonText' => 'Update Category'])
        </form>
    </div>
</div>
@endsection

resources/views/admin/categories/form.blade.php
@csrf
<div class="card-body">
    <div class="form-group">
        <label for="name">Jenis Kategory Berita</label>
        <input type="text" name="name" id="name" class="form-control" value="{{$category->name}}">
    </div>
    <div class="form-group">
        <button class="btn btn-success" type="submit">{{$buttonText}}</button>
    </div>
</div>

resources/views/admin/categories/index.blade.php
 @extends('admin.app')
 @section('content')
 <div class="card">
     <div class="card-header">Kategori</div>
     <div class="card-body">
         <a href="{{route('categories.create')}}" class="btn btn-success btn-sm m-2">Tambah Kategory</a>
         @if($categories->count())
         <table class="table">
             <thead>
                 <th>Nama</th>
                 <th>Aksi</th>
                 <th></th>
             </thead>
             <tbody>
                 @foreach($categories as $category)
                 <tr>
                     <h5>
                         <td> {{$category->name}}</td>
                         <td>
                             <div class="row">
                                 <span class="">
                                     <a href="{{route('categories.edit', $category)}}">
                                         <i class="nav-icon fas fa-edit"></i>
                                     </a>
                                 </span>
                                 <form action="{{route('categories.destroy', $category)}}" method="POST">
                                     @csrf
                                     @method('DELETE')
                                     <span class="mx-4">
                                         <button class="border-0 bg-light" type="submit">
                                             <i class="nav-icon fas fa-trash text-danger"></i>
                                         </button>
                                 </form>
                             </div>
                         </td>
                     </h5>
                 </tr>
                 @endforeach
             </tbody>
         </table>
         @else
         <center>Belum ada kategory Berita</center>
         @endif

     </div>
 </div>
 @endsection